---
title: "1st try"
author: "Bikash Gupta"
date: "2023-02-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}

# install.packages('leaflet')

```

```{r}
library(leaflet)

m <- leaflet(options = leafletOptions(minZoom = 0, maxZoom = 18)) %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=174.768, lat=-36.852, popup="The birthplace of R")

m
```


```{r}

#m <- leaflet() %>% addTiles() %>% setView(-71.0382679, 42.3489054, zoom = 18)
#m %>% fitBounds(-72, 40, -70, 43)
m %>% clearBounds()
#m

```


```{r}
df = data.frame(Lat = 1:10, Long = rnorm(10))
leaflet(df) %>% addCircles()


```

```{r}
leaflet(df) %>% addCircles(lng = ~Long, lat = ~Lat)

```


```{r}

library(sp)
Sr1 = Polygon(cbind(c(3, 9, 9, 1, 2), c(2, 3, 5, 4, 2)))
Sr2 = Polygon(cbind(c(5, 4, 2, 5), c(2, 3, 2, 2)))
Sr3 = Polygon(cbind(c(4, 4, 5, 10, 4), c(5, 3, 2, 5, 5)))
Sr4 = Polygon(cbind(c(5, 6, 6, 5, 5), c(4, 4, 3, 3, 4)), hole = TRUE)
Srs1 = Polygons(list(Sr1), "s1")
Srs2 = Polygons(list(Sr2), "s2")
Srs3 = Polygons(list(Sr4, Sr3), "s3/4")
SpP = SpatialPolygons(list(Srs1, Srs2, Srs3), 1:3)
leaflet(height = "300px") %>% addPolygons(data = SpP)

```


```{r}
library(maps)
mapStates = map("county
                ", fill = TRUE, plot = FALSE)
leaflet(data = mapStates) %>% addTiles() %>%
  addPolygons(fillColor = topo.colors(10, alpha = NULL), stroke = FALSE)

```


```{r}

m = leaflet() %>% addTiles()
df = data.frame(
  lat = rnorm(100),
  lng = rnorm(100),
  size = runif(100, 5, 20),
  color = sample(colors(), 100)
)
m = leaflet(df) %>% addTiles()
m %>% addCircleMarkers(radius = ~size, color = ~color, fill = FALSE)
m %>% addCircleMarkers(radius = runif(100, 4, 10), color = c('red'))

```


```{r}

n <- leaflet() %>% addTiles() %>% setView(lat=27.7172, lng=85.3240, zoom=18)
n

```


```{r}

n <- leaflet() %>% 
  addProviderTiles(providers$Esri.WorldPhysical) %>% 
  setView(lat=27.7172, lng=85.3240, zoom=18)
n


```